#!/usr/bin/env bash
# check if correct number of params were passed
if [[$# -lt 4]]; then
	#if not, display the usage message
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Set the variables from the params
file=$1
ip=$2
username=$3
key=$4

# TRansfer the file using scp with specified options
scp -i $key -o StrictHostKeyChecking=no $file $username@$ip:~/
