#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
sudo apt-get -y update
sudo apt-get -y install nginx

# add the following lines to the http block
sed -i 'http {/a \\\ add_header X-Served-By $hostname;' /etc/nginx/nginx.conf

# Save the changes and exit
# Restart the Nginx service to apply the changes
sudo nginx -s reload
