#!/usr/bin/env/ bash
# Script that makes a web server to run Nginx as the nginx user and listens on port 8080
# Create the "nginx" user and group
groupadd nginx
useradd -r -g nginx nginx

# Configure nginx to run as the "nginx" user and group
sed -i 's/user  nobody;/user  nginx nginx;/g' /etc/nginx/nginx.conf

# Configure nginx to listen on all active IP addresses on port 8080
sed -i 's/listen       80;/listen       0.0.0.0:8080;/g' /etc/nginx/nginx.conf

# Change the ownership of the nginx directories and files to the "nginx" user and group
chown -R nginx:nginx /usr/local/nginx

# Allow incoming traffic on port 8080
iptables -A INPUT -p tcp --dport 8080 -j ACCEPT

# Save the iptables rules
iptables-save > /etc/iptables.conf

# Restart the nginx server
systemctl restart nginx

